(()=>{"use strict";
const V="2026-08-24-sl-toji-final-v3",ST="lifeWheelBattleBridge",DK="jjk-life-wheel-story-cpu-difficulty-v2",DRAFT="jjk-life-wheel-run-draft-v1",SL="jjk-life-wheel-sl-slot-v1-",CAP=.38;
window.JJK_LIFE_WHEEL_PATCH_V3=V;
const C=v=>{try{return structuredClone(v)}catch{try{return JSON.parse(JSON.stringify(v))}catch{return v&&typeof v==="object"?{...v}:v}}},N=v=>["easy","normal","hard"].includes(String(v||"").toLowerCase())?String(v).toLowerCase():"normal",GD=()=>{try{return N(localStorage.getItem(DK)||"normal")}catch{return"normal"}},SD=v=>{v=N(v);try{localStorage.setItem(DK,v);localStorage.setItem("jjk-duel-cpu-difficulty-v1",v)}catch{}let a=document.querySelector("#duelCpuDifficultySelect"),b=document.querySelector("#jjkStoryDifficultySelect");if(a)a.value=v;if(b)b.value=v;return v};
const TXT=a=>{let p=a?.characterCardProfile||a?.profile||a||{};return[a?.id,a?.name,p?.id,p?.characterId,p?.name,p?.displayName,...(p?.traits||[]),...(p?.cardTags||[]),...(p?.specialHandTags||[])].filter(Boolean).join(" ")},TOJI=a=>/toji_fushiguro_hidden_inventory|伏黑甚尔（怀玉|伏黑甚尔.*完整咒具/i.test(TXT(a)),UNIT=x=>Number(x?.combatPowerUnit?.value||x?.characterCardProfile?.combatPowerUnit?.value||x?.profile?.combatPowerUnit?.value||0),PEER=(a,d)=>{let A=UNIT(a),D=UNIT(d);if(A>0&&D>0)return D>=A*.6;return Number(d?.maxHp||d?.hp||1)>=Number(a?.maxHp||a?.hp||1)*.6};
function fixResult(v,h){if(!v||typeof v!=="object")return;let s=new Set,walk=o=>{if(!o||typeof o!=="object"||s.has(o))return;s.add(o);if(o.targetType==="character"){if("defeated"in o)o.defeated=false;if("overkill"in o)o.overkill=0;if("afterHp"in o)o.afterHp=+h.toFixed(1)}Array.isArray(o)?o.forEach(walk):Object.values(o).forEach(walk)};walk(v)}
function installToji(){let a=globalThis.JJKDuelActions;if(!a||typeof a.applyDuelActionEffect!=="function")return false;if(a.applyDuelActionEffect.__v3)return true;let o=a.applyDuelActionEffect,w=function(ac,x,y,b){let before=Number(y?.hp||0),max=Math.max(1,Number(y?.maxHp||before||1)),guard=TOJI(x)&&PEER(x,y)&&before>max*CAP,r=o.call(this,ac,x,y,b);if(guard&&y){let after=Number(y.hp||0),loss=Math.max(0,before-after),cap=max*CAP;if(loss>cap){let h=Math.max(0,before-cap);y.hp=h;fixResult(r,h);try{(b?.resourceLog||b?.log)?.unshift?.({side:y.side||"left",title:"同级爆发保护",detail:`伏黑甚尔本行动原本造成 ${loss.toFixed(1)} 体势损失；同级单行动上限 ${cap.toFixed(1)}，修正后 ${h.toFixed(1)}/${max.toFixed(1)}。`,type:"system",delta:{tojiPeerBurstGuard:true,originalLoss:loss,cappedLoss:cap}})}catch{}}}return r};Object.defineProperty(w,"__v3",{value:true});a.applyDuelActionEffect=w;return true}
function liveDifficulty(){if(typeof state==="undefined")return;let b=state.duelBattle;if(String(b?.activityContext?.type||"")!==ST)return;let d=GD(),L={easy:"简单：陪练",normal:"普通：稳定",hard:"困难：强规划"};b.cpuDifficulty=d;b.cpuDifficultyLabel=L[d];let s=document.querySelector("#duelCpuDifficultySelect");if(s&&s.value!==d)s.value=d}
function save(slot){if(typeof globalThis.buildLifeWheelRunDraftPayload!=="function"||typeof state==="undefined")return alert("人生转盘还没初始化好。"),false;if(state.isSpinning)return alert("先等本次转盘停下再存档。"),false;let p=globalThis.buildLifeWheelRunDraftPayload();p.__sl={slot,savedAt:new Date().toISOString(),pendingResult:C(state.pendingResult||null)};try{localStorage.setItem(SL+slot,JSON.stringify(p));meta();tip(`S${slot} 已存档`);return true}catch(e){alert("存档失败："+(e?.message||e));return false}}
function load(slot){let raw="";try{raw=localStorage.getItem(SL+slot)||""}catch{}if(!raw)return alert(`S${slot} 为空。`),false;let p;try{p=JSON.parse(raw)}catch{return alert(`S${slot} 存档损坏。`),false}if(!confirm(`读取 S${slot}？当前未保存进度会被覆盖。`))return false;try{globalThis.JJKDuelRuntime?.clearCurrentDuelBattle?.({render:false});localStorage.setItem(DRAFT,raw);if(!globalThis.restoreLifeWheelRunDraft?.())throw Error("存档与当前版本不兼容");state.pendingResult=C(p?.__sl?.pendingResult||null);globalThis.renderAll?.();globalThis.saveLifeWheelRunDraft?.();closeSL();tip(`L${slot} 读取完成`);return true}catch(e){alert("读档失败："+(e?.message||e));return false}}
function info(i){try{let r=localStorage.getItem(SL+i);if(!r)return null;let p=JSON.parse(r);return{t:p?.__sl?.savedAt||p?.savedAt||"",n:p?.run?.records?.length||0,x:p?.run?.currentTask?.title||"角色流程"}}catch{return null}}
function meta(){for(let i=1;i<=3;i++){let e=document.querySelector(`#jjkSlMeta${i}`),m=info(i);if(e)e.textContent=m?`${new Date(m.t).toLocaleString("zh-CN",{hour12:false})}｜${m.x}｜记录${m.n}`:"空槽"}}
function closeSL(){document.querySelector("#jjkSlOverlay")?.remove()}
function openSL(){closeSL();let d=document.createElement("div");d.id="jjkSlOverlay";d.innerHTML=`<div class="jjk-sl-card"><div class="jjk-sl-head"><strong>💾 SL 存档 / 读档</strong><button data-x>×</button></div><p>保存整个人生转盘状态。建议战斗前 S，想重来就 L；不保存战斗中的具体回合。</p>${[1,2,3].map(i=>`<div class="jjk-sl-row"><div><b>S${i}</b><small id="jjkSlMeta${i}">读取中</small></div><button data-s="${i}">保存</button><button data-l="${i}">读取</button></div>`).join("")}</div>`;document.body.appendChild(d);d.onclick=e=>{let b=e.target.closest("button");if(!b){if(e.target===d)closeSL();return}if(b.hasAttribute("data-x"))closeSL();if(b.dataset.s)save(+b.dataset.s);if(b.dataset.l)load(+b.dataset.l)};meta()}
function graded(){return typeof state!=="undefined"&&!!(state.answers?.grade||(state.records||[]).some(r=>String(r?.title||"").includes("等级判定")))}
async function runChar(){if(typeof state==="undefined"||typeof globalThis.getAutoResultForTask!=="function"||typeof globalThis.acceptAndAdvance!=="function")return alert("自动车人模块还没初始化。"),false;if(state.isSpinning)return false;if(graded()){if(!confirm("当前角色已经确定。重新随机车一个新角色？"))return false;globalThis.restart?.({clearDraft:true});await new Promise(r=>setTimeout(r,0))}let b=document.querySelector("#jjkRunToCharacterBtn"),old=b?.textContent||"一键车完角色";if(b){b.disabled=true;b.textContent="正在车角色…"}let n=0;try{state.spinToken+=1;state.pendingResult=null;state.isSpinning=false;while(state.currentTask?.type!=="end"&&n<500){let t=state.currentTask,r=globalThis.getAutoResultForTask(t);if(!r)break;state.pendingResult=r;globalThis.acceptAndAdvance({render:false});n++;if(t?.nodeId==="grade")break}globalThis.saveLifeWheelRunDraft?.();globalThis.renderAll?.();tip(graded()?`角色构筑完成｜${n}步`:`自动车人中止｜${n}步`);return graded()}catch(e){console.error(e);alert("一键车人失败："+(e?.message||e));return false}finally{if(b){b.disabled=false;b.textContent=old}}}
function tip(t){let e=document.querySelector("#jjkQuickStatus");if(!e)return;e.textContent=t;clearTimeout(tip._t);tip._t=setTimeout(()=>{if(e)e.textContent=""},3500)}
function ui(){if(document.querySelector("#jjkRunToCharacterBtn"))return true;let r=document.querySelector("#runAllBtn");if(!r?.parentElement)return false;let a=document.createElement("button");a.id="jjkRunToCharacterBtn";a.className="secondary";a.textContent="一键车完角色";a.onclick=()=>runChar();let s=document.createElement("button");s.id="jjkSlBtn";s.className="secondary";s.textContent="SL 存读档";s.onclick=openSL;let d=document.createElement("select");d.id="jjkStoryDifficultySelect";d.title="剧情敌方电脑难度";d.innerHTML='<option value="easy">敌方：简单</option><option value="normal">敌方：普通</option><option value="hard">敌方：困难</option>';d.value=GD();d.onchange=()=>SD(d.value);let q=document.createElement("span");q.id="jjkQuickStatus";q.className="muted";r.after(a);a.after(s);s.after(d);d.after(q);return true}
function css(){if(document.querySelector("#jjkV3Style"))return;let s=document.createElement("style");s.id="jjkV3Style";s.textContent='#jjkStoryDifficultySelect{min-height:38px;border-radius:10px;border:1px solid #ffffff2e;background:#1b1b22;color:#fff;padding:0 10px;font:inherit}#jjkSlOverlay{position:fixed;inset:0;z-index:2147483600;background:#000b;display:grid;place-items:center;padding:16px;backdrop-filter:blur(8px)}.jjk-sl-card{width:min(620px,100%);background:#15151b;color:#f6f4ff;border:1px solid #ffffff2e;border-radius:20px;padding:18px;box-shadow:0 30px 90px #0009;font:14px/1.55 system-ui,-apple-system,sans-serif}.jjk-sl-head{display:flex;align-items:center;justify-content:space-between;font-size:20px}.jjk-sl-head button{border:0;background:transparent;color:#fff;font-size:30px}.jjk-sl-row{display:grid;grid-template-columns:minmax(0,1fr) auto auto;gap:8px;align-items:center;padding:10px 0;border-top:1px solid #ffffff17}.jjk-sl-row small{display:block;opacity:.7;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.jjk-sl-row button{border:1px solid #ffffff2e;background:#292934;color:#fff;border-radius:10px;padding:9px 12px;font-weight:700}@media(max-width:640px){.jjk-sl-row{grid-template-columns:1fr 72px 72px}.jjk-sl-card{padding:14px}}';document.head.appendChild(s)}
function tick(){css();installToji();ui();liveDifficulty()}
window.JJKLifeWheelV3={version:V,saveSlot:save,loadSlot:load,runToCharacterComplete:runChar,getStoryDifficulty:GD,setStoryDifficulty:SD};
try{if(!localStorage.getItem(DK))SD("normal")}catch{SD("normal")}
tick();setInterval(tick,60);console.info(`[JJK-Life-Wheel] supplement loaded: ${V}`)
})();