(()=>{"use strict";
const V="2026-08-24-toji-soft-burst-v3c",THRESH=.34,TAIL=.28;
const txt=a=>{let p=a?.characterCardProfile||a?.profile||a||{};return[a?.id,a?.name,p?.id,p?.characterId,p?.name,p?.displayName,p?.visibleGrade,p?.officialGrade,p?.powerTier,p?.baseStats?.martial,p?.stats?.martial,...(p?.traits||[]),...(p?.cardTags||[])].filter(Boolean).join(" ")};
const toji=a=>/toji_fushiguro_hidden_inventory|伏黑甚尔（怀玉|伏黑甚尔.*完整咒具/i.test(txt(a));
const unit=x=>Number(x?.combatPowerUnit?.value||x?.characterCardProfile?.combatPowerUnit?.value||x?.profile?.combatPowerUnit?.value||0);
const rank=x=>String(x?.characterCardProfile?.baseStats?.martial||x?.characterCardProfile?.stats?.martial||x?.profile?.baseStats?.martial||x?.profile?.stats?.martial||"");
const strongMartial=x=>/^(S|SS|SSS|EX-|EX)$/i.test(rank(x));
const peer=(a,d)=>{if(!a||!d)return false;let hp=Math.max(1,Number(d.maxHp||d.hp||1))/Math.max(1,Number(a.maxHp||a.hp||1)),uA=unit(a),uD=unit(d),grade=/specialGrade|特级/i.test(txt(d));return hp>=.50||grade||strongMartial(d)||(uA>0&&uD>0&&uD>=uA*.50)};
function fix(v,h){if(!v||typeof v!=="object")return;let seen=new Set,walk=o=>{if(!o||typeof o!=="object"||seen.has(o))return;seen.add(o);if(o.targetType==="character"){if("defeated"in o)o.defeated=h<=0;if("overkill"in o)o.overkill=0;if("afterHp"in o)o.afterHp=+h.toFixed(1)}Array.isArray(o)?o.forEach(walk):Object.values(o).forEach(walk)};walk(v)}
function install(){let api=globalThis.JJKDuelActions;if(!api||typeof api.applyDuelActionEffect!=="function")return false;if(api.applyDuelActionEffect.__v3c)return true;let old=api.applyDuelActionEffect,wrap=function(action,actor,defender,battle){let before=Number(defender?.hp||0),max=Math.max(1,Number(defender?.maxHp||before||1)),guard=toji(actor)&&peer(actor,defender)&&before>max*.24,result=old.call(this,action,actor,defender,battle);if(guard&&defender){let after=Number(defender.hp||0),loss=Math.max(0,before-after),knee=max*THRESH;if(loss>knee){let softened=knee+(loss-knee)*TAIL;softened=Math.min(loss,softened);let restored=Math.max(0,before-softened);if(restored>after+.4){defender.hp=+restored.toFixed(1);fix(result,restored);try{(battle?.resourceLog||battle?.log)?.unshift?.({side:defender.side||"left",title:"甚尔爆发软压缩",detail:`本行动原造成 ${loss.toFixed(1)} 体势损失；前 ${(THRESH*100).toFixed(0)}% 正常兑现，超出部分按 ${(TAIL*100).toFixed(0)}% 递减兑现，最终 ${softened.toFixed(1)}。`,type:"system",delta:{tojiSoftBurst:true,originalLoss:loss,softenedLoss:softened,knee}})}catch{}}}}return result};Object.defineProperty(wrap,"__v3c",{value:true});api.applyDuelActionEffect=wrap;console.info(`[JJK-Life-Wheel] patch loaded: ${V}`);return true}
let n=0,t=setInterval(()=>{if(install()||++n>300)clearInterval(t)},50);install();window.JJKTojiBurstV3C={version:V,threshold:THRESH,tail:TAIL};
})();