(()=>{"use strict";
const V="2026-08-24-technique-power-v4";
const RANK_BOOST={"E-":.82,E:.86,D:.9,C:.95,B:1,A:1.12,S:1.32,SS:1.52,SSS:1.82,"EX-":2.08,EX:2.34};
const RANK_FLOOR={S:.035,SS:.055,SSS:.08,"EX-":.105,EX:.13};
const HIGH_FLOOR={S:.08,SS:.12,SSS:.18,"EX-":.22,EX:.26};
const ULT_FLOOR={S:.14,SS:.21,SSS:.31,"EX-":.37,EX:.43};
const A=v=>Array.isArray(v)?v:v==null?[]:[v];
const text=x=>{const p=x?.characterCardProfile||x?.profile||x||{};return [x?.id,x?.actionId,x?.cardId,x?.label,x?.name,x?.type,x?.cardType,x?.scalingProfile,x?.damageType,x?.risk,x?.effectSummary,...A(x?.tags),...A(x?.specialHandTags),p?.displayName,p?.name,p?.techniquePower,p?.techniques?.[0]?.power,p?.techniqueName,p?.techniqueText].filter(Boolean).join(" ")};
const actorProfile=a=>a?.characterCardProfile||a?.profile||a||{};
function techRank(a){const p=actorProfile(a);let r=String(p.techniquePower||p.techniques?.[0]?.power||p.technique?.power||p.raw?.techniquePower||"").trim().toUpperCase();return RANK_BOOST[r]?r:"B"}
function isTechniqueAction(action){const t=text(action).toLowerCase();if(/heal|healing|rct|reverse|治疗|疗伤|回复|support|resource|defense|guard|防御|格挡|cursed_tool|咒具|weapon|刀|剑|melee|physical|martial|体术|近身|拳|踢|零咒力|zero_ce/.test(t))return false;return /technique|innate|术式|咒法|咒术|curse|projectile|beam|burst|领域|domain|必中|sure_hit|blue|red|purple|苍|赫|茈|斩击|slash|shrine|御厨子|maximum/.test(t)}
function tier(action,result,actor){const t=text(action).toLowerCase();const cost=Number(result?.costCe??result?.cost?.ce??action?.cost?.ce??action?.ceCost??0);const maxCe=Math.max(1,Number(actor?.maxCe||actor?.ce||1));const ratio=cost/maxCe;if(/茈|虚式|hollow.?purple|极之番|極ノ番|maximum|最大出力|最大输出|奥义|奧義|终结|終結|finisher|ultimate|灶.?开|fuga|世界斩|world.?slash/.test(t))return"ultimate";if(/critical|high|burst|爆发|大功率|高出力|高输出|领域|domain/.test(t)||ratio>=.1)return"high";return"normal"}
function floorRatio(rank,t){return (t==="ultimate"?ULT_FLOOR:t==="high"?HIGH_FLOOR:RANK_FLOOR)[rank]||0}
function peer(a,d){const p=actorProfile(a),q=actorProfile(d);const ta=text(p),td=text(q);if(/特级|special.?grade/i.test(ta)&&/特级|special.?grade/i.test(td))return true;const ah=Math.max(1,Number(a?.maxHp||a?.hp||1)),dh=Math.max(1,Number(d?.maxHp||d?.hp||1));return dh/ah>=.5&&dh/ah<=2}
function updateResult(result,bonus,defender){if(!result||typeof result!=="object")return;for(const k of ["directDamage","opponentHpDamage","damage"]){if(Number.isFinite(Number(result[k]))&&Number(result[k])>0)result[k]=Number((Number(result[k])+bonus).toFixed(1))}if(result.damageApplication&&typeof result.damageApplication==="object"){if(Number.isFinite(Number(result.damageApplication.applied)))result.damageApplication.applied=Number((Number(result.damageApplication.applied)+bonus).toFixed(1));result.damageApplication.afterHp=Number(defender.hp.toFixed(1));result.damageApplication.defeated=defender.hp<=0}result.techniquePowerBonusDamage=Number(bonus.toFixed(1))}
function install(){const api=globalThis.JJKDuelActions;if(!api||typeof api.applyDuelActionEffect!=="function")return false;if(api.applyDuelActionEffect.__techPowerV4)return true;const old=api.applyDuelActionEffect;const wrap=function(action,actor,defender,battle){const before=Number(defender?.hp||0),max=Math.max(1,Number(defender?.maxHp||before||1));const rank=techRank(actor),eligible=isTechniqueAction(action)&&RANK_BOOST[rank]>1;const result=old.call(this,action,actor,defender,battle);if(!eligible||!defender||before<=0)return result;const after=Number(defender.hp||0),applied=Math.max(0,before-after);if(applied<=0)return result;const mode=tier(action,result,actor),boost=RANK_BOOST[rank]||1;let desired=applied*boost;const floor=max*floorRatio(rank,mode);if(peer(actor,defender)||mode!=="normal")desired=Math.max(desired,floor);desired=Math.min(desired,before);const bonus=Math.max(0,desired-applied);if(bonus<.5)return result;defender.hp=Math.max(0,Number((after-bonus).toFixed(1)));updateResult(result,bonus,defender);try{(battle?.resourceLog||battle?.log)?.unshift?.({side:defender.side||"right",title:"术式威力兑现",detail:`${actor?.name||"术师"}的术式威力 ${rank} 对「${action?.label||action?.name||action?.id||"术式"}」生效：原实际伤害 ${applied.toFixed(1)} → ${desired.toFixed(1)}（${mode==="ultimate"?"终结技":mode==="high"?"高输出":"常规术式"}）。`,type:"system",delta:{techniquePowerRank:rank,techniquePowerBoost:boost,techniquePowerFloor:floor,techniquePowerBonus:bonus,techniquePowerMode:mode}})}catch{}return result};Object.defineProperty(wrap,"__techPowerV4",{value:true});api.applyDuelActionEffect=wrap;console.info(`[JJK-Life-Wheel] patch loaded: ${V}`);return true}
let n=0,t=setInterval(()=>{if(install()||++n>300)clearInterval(t)},50);install();window.JJKTechniquePowerV4={version:V,rankBoost:RANK_BOOST,normalFloor:RANK_FLOOR,highFloor:HIGH_FLOOR,ultimateFloor:ULT_FLOOR};
})();