(()=>{"use strict";
const V="2026-08-24-system-balance-v6",STORY="lifeWheelBattleBridge",RANK_SCORE={"E-":0,E:1,D:2,C:3,B:4,A:5,S:6.2,SS:7.4,SSS:8.8,"EX-":10.2,EX:12};
const ATTRS=["电击感｜咒力接触时产生短促麻痹与刺痛","灼热感｜咒力呈高温与灼烧触感","寒冷感｜咒力带走热量并产生冻结般触感","锋锐感｜咒力边缘具有切割与撕裂性质","震动感｜咒力接触会产生连续震颤与冲击","黏滞感｜咒力会附着、拖拽并扰乱动作","沉重感｜咒力接触后产生异常压迫与负重感","爆裂感｜咒力在接触点产生短促爆裂冲击","麻痹感｜咒力优先扰乱神经与动作节奏","腐蚀感｜咒力长时间接触会产生侵蚀性损伤"];
const NPARADE={low:["枷场菜菜子","枷场美美子"],mid:["枷场菜菜子","枷场美美子"],high:["米格尔","枷场菜菜子","枷场美美子"],special:["夏油杰","米格尔"]};
function clone(v){try{return structuredClone(v)}catch{try{return JSON.parse(JSON.stringify(v))}catch{return v&&typeof v==="object"?{...v}:v}}}
function rankScore(v){let k=String(v||"").trim().toUpperCase().match(/^(EX-|EX|SSS|SS|S|A|B|C|D|E-|E)/)?.[1];return RANK_SCORE[k]??NaN}
function profileOf(x){return x?.characterCardProfile||x?.profile||x||{}}
function isLifePlayer(profile){return /^战力导入：/.test(String(profile?.displayName||profile?.name||""))||/life-wheel|人生转盘|转盘导入/i.test(String(profile?.notes||profile?.source||""))||Boolean(profile?.encodedCombatProfile)}
function ceScore(profile){const p=profile||{},r=p.raw||{},s=p.baseStats||p.stats||{};for(const v of [r.cursedEnergyScore,p.cursedEnergyScore,s.cursedEnergy,p.cursedEnergy]){const n=Number(v);if(Number.isFinite(n))return Math.max(0,n);const q=rankScore(v);if(Number.isFinite(q))return q}return 0}
function techScore(profile){return Math.max(0,rankScore(profile?.techniquePower)||0)}
function installResource(){const api=globalThis.JJKDuelResource;if(!api||typeof api.deriveDuelResourcesFromProfile!=="function")return false;if(api.deriveDuelResourcesFromProfile.__v6)return true;const old=api.deriveDuelResourcesFromProfile,wrap=function(profile,card,side){const r=old.call(this,profile,card,side);if(!r||r.isZeroCe||!isLifePlayer(profile))return r;const ce=ceScore(profile),tech=techScore(profile),over=Math.max(0,ce-6),base=36+22*ce+1.6*over*over,bonusCap=6+4.5*ce,bonusRaw=tech*1.8,target=Math.max(18,Math.round(base+Math.min(bonusCap,bonusRaw)));r.maxCe=target;r.ce=target;r.ceRegen=Math.max(0,Number((target*Number(r.regenRatio||0)).toFixed(1)));r.v6CeModel={score:ce,techniqueScore:tech,target};return r};Object.defineProperty(wrap,"__v6",{value:true});api.deriveDuelResourcesFromProfile=wrap;return true}
function installDirectFormula(){const api=globalThis.JJKBattleDataDirect;if(!api||typeof api.calculateBattleCardSettlement!=="function")return false;if(api.__v6Formula)return true;const old=api.calculateBattleCardSettlement;const wrapped={...api,calculateBattleCardSettlement(card,actor,opponent,options){let c=card;if(card?.scaling){c=clone(card);c.scaling={...(c.scaling||{})};const s=c.scaling;if(Number(s.bodyResistancePerRank??.07)>=.055){s.bodyResistanceBase=.14;s.bodyResistancePerRank=.027;s.bodyResistanceMin=.015;s.bodyResistanceMax=.34}if(Number(s.martialEvasionPerRank??0)>=.04&&Number(s.martialEvasionPerRank??0)<=.055)s.martialEvasionPerRank=.020}return old.call(this,c,actor,opponent,options)},__v6Formula:true};try{globalThis.JJKBattleDataDirect=Object.freeze(wrapped);return true}catch{return false}}
function isStory(b){return String(b?.activityContext?.type||"")==="lifeWheelBattleBridge"}
function isDamage(a){return Number(a?.effect?.damage??a?.damage??a?.baseDamage??a?.numericPreview?.finalDamage??0)>0}
function isPhysical(a){const t=[a?.id,a?.name,a?.label,a?.damageType,a?.scalingProfile,...(a?.tags||[])].filter(Boolean).join(" ");return /melee|physical|martial|体术|近身|拳|踢|咒具|cursed_tool|weapon|刀|剑/i.test(t)}
function transcendBonus(physical){let m=state?.flags?.battleBridgeTranscendence||{},ids=physical?["body","martial"]:["cursedEnergy","control","efficiency"];let s=0;for(const id of ids){let n=Math.max(0,Math.trunc(Number(m[id]||0)));for(let i=1;i<=n;i++)s+=.24/(1+.55*(i-1))}return Math.min(.16,s*(physical?.055:.045))}
function scaleDamageFields(a,m){for(const [o,k] of [[a,"damage"],[a,"baseDamage"],[a.effect,"damage"]])if(o&&Number.isFinite(Number(o[k]))&&Number(o[k])>0)o[k]=Number((Number(o[k])*m).toFixed(4))}
function isGenericGeneratedAction(a){const schema=String(a?.schema||a?.cardSchema||"");return !a?.scaling&&a?.type!=="card_template_runtime"&&!/battle-card|direct-card/i.test(schema)}
function installActionBalance(){const api=globalThis.JJKDuelActions;if(!api||typeof api.applyDuelActionEffect!=="function")return false;if(api.applyDuelActionEffect.__v6)return true;const old=api.applyDuelActionEffect,wrap=function(action,actor,opponent,battle){let a=action;if(isStory(battle)&&String(actor?.side||"")==="left"&&isDamage(action)){a=clone(action);if(isGenericGeneratedAction(a)){const correction=/high|critical/i.test(String(a.risk||""))?(.76/.58):(.68/.45);scaleDamageFields(a,correction);a.__v6GenericSettlementCorrection=correction}const extra=transcendBonus(isPhysical(a));if(extra>0){scaleDamageFields(a,1+extra);a.__v6Transcendence=extra}}return old.call(this,a,actor,opponent,battle)};Object.defineProperty(wrap,"__v6",{value:true});api.applyDuelActionEffect=wrap;return true}
function age(){try{return Number(globalThis.getNumericLifeAge?.())||Number(String(state?.flags?.age||"").match(/\d+/)?.[0])||0}catch{return 0}}
function ageStatusFactor(text,a){let f=1;if(a<=22){if(text==="学生")f=1.25;else if(text==="老师")f=.28;else if(text==="校长"||text==="老登")f=.03}else if(a<=25){if(text==="学生")f=.55;else if(text==="老师")f=1.25;else if(text==="校长")f=.08;else if(text==="老登")f=.05}else if(a<=34){if(text==="学生")f=.02;else if(text==="老师")f=2.1;else if(text==="校长")f=.35;else if(text==="老登")f=.12}else if(a<=49){if(text==="学生")f=.01;else if(text==="老师")f=1.55;else if(text==="校长")f=1.35;else if(text==="老登")f=.5}else{if(text==="学生")f=.002;else if(text==="老师")f=.8;else if(text==="校长")f=1.75;else if(text==="老登")f=2.3}return f}
function installAgeWeights(){const old=globalThis.getAdjustedWeight;if(typeof old!=="function")return false;if(old.__v6)return true;const wrap=function(task,item,index,base,context){let w=Number(old.call(this,task,item,index,base,context))||0;if(task?.nodeId!=="highSchoolStatus")return w;const a=age();if(!a)return w;return Math.max(0,w*ageStatusFactor(String(item?.text||""),a))};Object.defineProperty(wrap,"__v6",{value:true});globalThis.getAdjustedWeight=wrap;return true}
function gradeBucket(){let s=String(state?.flags?.sorcererGradeLabel||state?.flags?.sorcererGrade||"");if(/特级/.test(s))return"special";if(/一级/.test(s)&&!/准一级/.test(s))return"high";if(/准一级/.test(s))return"mid";return"low"}
function patchNightParadeTask(){const t=state?.currentTask;if(!t||!/百鬼夜行结果（高专方）/.test(String(t.title||"")))return false;if(t.__v6NightParade)return true;let pool=NPARADE[gradeBucket()]||NPARADE.low;t.battleBridgeOpponents=pool.slice();t.__v6NightParade=true;t.why=`${t.why||""}｜V6：百鬼夜行按当前术师等级匹配敌手；只有特级/明确终局路线才默认可能遭遇夏油杰。`;return true}
const RANKS=["E-","E","D","C","B","A","S","SS","SSS","EX-","EX"];
function baseRank(id){let v=state?.flags?.battleBridgePersistentRanks?.[id]||state?.answers?.[id]?.rawText||state?.answers?.[id]?.text||state?.answers?.[id]?.result||"";return String(v).toUpperCase().match(/^(EX-|EX|SSS|SS|S|A|B|C|D|E-|E)/)?.[1]||"B"}
function stepRankLabel(r,d){let i=RANKS.indexOf(r);if(i<0)i=4;return RANKS[Math.max(0,Math.min(RANKS.length-1,i+d))]}
function applyEraRank(id,delta){state.flags||={};state.flags.battleBridgePersistentRanks||={};let from=baseRank(id);if(delta>0&&from==="EX"){state.flags.battleBridgeTranscendence||={};state.flags.battleBridgeTranscendence[id]=Math.max(0,Number(state.flags.battleBridgeTranscendence[id]||0))+1;return `${from}→EX+${state.flags.battleBridgeTranscendence[id]}`}let to=stepRankLabel(from,delta);state.flags.battleBridgePersistentRanks[id]=to;return `${from}→${to}`}
function effortScore(){let t=String(state?.flags?.effortLevel||"");if(/持之以恒|刻苦|拼命|极度努力/.test(t))return 3;if(/努力|认真/.test(t))return 2;if(/一般|普通/.test(t))return 1;if(/摆烂|不努力|躺平/.test(t))return 0;return 1}
function makeEraGapTask(){let e=effortScore(),tal=RANKS.indexOf(baseRank("talent")),grow=Math.min(88,22+e*18+Math.max(0,tal)*3),decline=e===0?24:e===1?7:2,roll=Math.random()*100,ids=["cursedEnergy","control","efficiency","body","martial"],zero=false;try{zero=!!globalThis.isZeroCursedEnergyHeavenlyRestriction?.()}catch{}if(zero)ids=ids.filter(x=>!["cursedEnergy","control","efficiency"].includes(x));let id=ids[Math.floor(Math.random()*ids.length)]||"martial",effect={kind:"maintain"},text="十年间能力大体维持｜经历增长，但没有形成明确等级变化";if(roll<decline){effect={kind:"rank",id,delta:-1};text=`长期懈怠/状态下滑｜${id}`}else if(roll<decline+grow){effect={kind:"rank",id,delta:1};text=`时代间积累形成突破｜${id}`}return{type:"computed",nodeId:"eraGapHiddenToVolume0",title:"时代间成长｜怀玉→0卷（约10年）",stage:"时代推进",why:`怀玉到0卷存在多年时间差，不能把角色能力完全冻结。努力程度：${state?.flags?.effortLevel||"一般"}；成长概率约${grow}%，退步概率约${decline}%。`,computedOption:{text,index:0,weight:1,bridgeEffect:effect},options:[{text}]}}
function maybeQueueEraGap(task){if(task?.title!=="保卫理子后"||state?.flags?.dead||state?.flags?.eraGapHiddenToVolume0Queued)return;state.flags.eraGapHiddenToVolume0Queued=true;state.taskQueue.unshift(makeEraGapTask())}
function applyEraGap(task,result,recordId){if(task?.nodeId!=="eraGapHiddenToVolume0")return;let e=result?.option?.bridgeEffect||task?.computedOption?.bridgeEffect;if(e?.kind==="rank"){let detail=applyEraRank(e.id,Number(e.delta||0)),labels={cursedEnergy:"咒力总量",control:"咒力操纵",efficiency:"咒力效率",body:"体质",martial:"体术"},rec=(state.records||[]).find(x=>Number(x?.id)===Number(recordId));if(rec)rec.result=`${e.delta>0?"长期积累形成突破":"长期状态下滑"}｜${labels[e.id]||e.id} ${detail}`}}
function makeAttributeTask(){return{type:"choice",nodeId:"cursedEnergyAttributeDetail",title:"咒力属性｜具体性质",stage:"能力风味",why:"已抽到具有属性的咒力，继续确定具体触感/性质，供故事与后续机制使用。",options:ATTRS.map(text=>({text}))}}
function findRecord(node){return [...(state?.records||[])].reverse().find(r=>String(r?.nodeId||"")===String(node))}
function installStoryHook(){const w=globalThis.JJKPersonalWheel,old=w?.afterCommit;if(typeof old!=="function")return false;if(old.__v6)return true;const wrap=function(payload){const ret=old.apply(this,arguments);try{const t=payload?.task,r=payload?.result;maybeQueueEraGap(t);applyEraGap(t,r,payload?.recordId);if(t?.nodeId==="cursedEnergyNature"&&/具有属性/.test(String(r?.text||""))&&!state.flags.cursedEnergyAttributeDetail&&!(state.taskQueue||[]).some(x=>x?.nodeId==="cursedEnergyAttributeDetail")){state.taskQueue.unshift(makeAttributeTask())}if(t?.nodeId==="cursedEnergyAttributeDetail"){state.flags.cursedEnergyAttributeDetail=String(r?.text||"");const rec=findRecord("cursedEnergyNature");if(rec&&!String(rec.result||"").includes("具体："))rec.result=`${rec.result}｜具体：${r.text}`}}catch(e){console.error("V6剧情补丁失败",e)}return ret};Object.defineProperty(wrap,"__v6",{value:true});w.afterCommit=wrap;return true}
function installBridgeMatcher(){const b=globalThis.JJKBattleStoryBridge;if(!b)return false;let ok=true;for(const key of ["maybeTriggerBattle","autoResolveCurrentTask"]){const old=b[key];if(typeof old!=="function"){ok=false;continue}if(old.__v6Match)continue;const wrap=function(...args){try{patchNightParadeTask()}catch{}return old.apply(this,args)};Object.defineProperty(wrap,"__v6Match",{value:true});b[key]=wrap}return ok}
function cleanOldAttributeOnRestart(){const w=globalThis.JJKPersonalWheel,old=w?.onRestart;if(typeof old!=="function"||old.__v6)return typeof old==="function";const wrap=function(...a){const r=old.apply(this,a);try{delete state.flags.cursedEnergyAttributeDetail;delete state.flags.eraGapHiddenToVolume0Queued}catch{}return r};Object.defineProperty(wrap,"__v6",{value:true});w.onRestart=wrap;return true}
function tick(){installResource();installDirectFormula();installActionBalance();installAgeWeights();installStoryHook();installBridgeMatcher();cleanOldAttributeOnRestart();patchNightParadeTask();if(typeof document!=="undefined")document.documentElement.dataset.jjkSystemBalance=V}
window.JJKLifeWheelV6={version:V};tick();setInterval(tick,100);console.info(`[JJK-Life-Wheel] system balance loaded: ${V}`);
})();