(()=>{"use strict";
const V="7.0.0",DK="jjk-life-wheel-story-cpu-difficulty-v7",SL="jjk-life-wheel-sl-slot-v7-",DRAFT="jjk-life-wheel-run-draft-v1",R=["E-","E","D","C","B","A","S","SS","SSS","EX-","EX"];
const ATTR=["电击感｜接触时产生短促麻痹与刺痛","灼热感｜咒力呈高温与灼烧触感","寒冷感｜咒力带走热量","锋锐感｜咒力具有切割性质","震动感｜接触产生连续震颤","黏滞感｜附着并拖拽动作","沉重感｜产生异常负重","爆裂感｜接触点产生爆裂冲击","麻痹感｜扰乱神经与动作节奏","腐蚀感｜长时间接触产生侵蚀损伤"];
const PARADE={low:["枷场菜菜子","枷场美美子"],mid:["枷场菜菜子","枷场美美子"],high:["米格尔","枷场菜菜子","枷场美美子"],special:["夏油杰","米格尔"]};
const C=v=>{try{return structuredClone(v)}catch{try{return JSON.parse(JSON.stringify(v))}catch{return v}}},N=v=>["easy","normal","hard"].includes(String(v||"").toLowerCase())?String(v).toLowerCase():"normal";
function gd(){try{return N(localStorage.getItem(DK)||"normal")}catch{return"normal"}}function sd(v){v=N(v);try{localStorage.setItem(DK,v);localStorage.setItem("jjk-duel-cpu-difficulty-v1",v)}catch{}for(const id of["duelCpuDifficultySelect","jjkV7Difficulty"]){let e=document.getElementById(id);if(e)e.value=v}return v}
function installDifficulty(){try{if(!localStorage.getItem(DK))sd("normal")}catch{}let r=state?.techniqueHandRules?.cpuDifficulty;if(r?.options){r.default="normal";r.options.normal={...(r.options.normal||{}),label:"普通：稳定",beamWidth:2,scoreNoise:.035,mistakeRate:.05,mistakePool:2};r.options.hard={...(r.options.hard||{}),label:"困难：强规划",beamWidth:5,scoreNoise:0,mistakeRate:0,mistakePool:1}}let f=globalThis.startDuelBattle;if(typeof f==="function"&&!f.__v7app){let o=f,w=function(opt={}){let n=String(opt?.activityContext?.type||"")==="lifeWheelBattleBridge"?{...opt,cpuDifficulty:gd()}:opt,r=o.call(this,n);if(String(n?.activityContext?.type||"")==="lifeWheelBattleBridge"&&state?.duelBattle)state.duelBattle.cpuDifficulty=gd();return r};Object.defineProperty(w,"__v7app",{value:true});globalThis.startDuelBattle=w}if(state?.duelBattle&&String(state.duelBattle.activityContext?.type||"")==="lifeWheelBattleBridge")state.duelBattle.cpuDifficulty=gd();return true}
function save(i){if(typeof state==="undefined"||typeof buildLifeWheelRunDraftPayload!=="function")return alert("转盘尚未初始化"),false;if(state.isSpinning)return alert("先等转盘停下"),false;let p=buildLifeWheelRunDraftPayload();p.__slV7={savedAt:new Date().toISOString(),pendingResult:C(state.pendingResult||null)};try{localStorage.setItem(SL+i,JSON.stringify(p));tip(`S${i} 已存档`);return true}catch(e){alert("存档失败："+(e?.message||e));return false}}
function load(i){let x="";try{x=localStorage.getItem(SL+i)||""}catch{}if(!x)return alert(`S${i} 为空`),false;if(!confirm(`读取 S${i}？当前未保存进度会被覆盖。`))return false;try{JJKDuelRuntime?.clearCurrentDuelBattle?.({render:false});localStorage.setItem(DRAFT,x);if(!restoreLifeWheelRunDraft?.())throw Error("存档不兼容");let p=JSON.parse(x);state.pendingResult=C(p.__slV7?.pendingResult||null);renderAll?.();saveLifeWheelRunDraft?.();document.getElementById("jjkV7SL")?.remove();tip(`L${i} 完成`);return true}catch(e){alert("读档失败："+(e?.message||e));return false}}
function openSL(){document.getElementById("jjkV7SL")?.remove();let d=document.createElement("div");d.id="jjkV7SL";d.innerHTML=`<div class="v7card"><div class="v7head"><b>💾 SL 存读档</b><button data-x>×</button></div><p>建议战斗前存档。战斗中的具体回合不做快照。</p>${[1,2,3].map(i=>`<div class="v7row"><b>S${i}</b><button data-s="${i}">保存</button><button data-l="${i}">读取</button></div>`).join("")}</div>`;document.body.appendChild(d);d.onclick=e=>{let b=e.target.closest("button");if(!b){if(e.target===d)d.remove();return}if(b.hasAttribute("data-x"))d.remove();if(b.dataset.s)save(+b.dataset.s);if(b.dataset.l)load(+b.dataset.l)}}
function graded(){return !!(state?.answers?.grade||(state?.records||[]).some(r=>String(r?.title||"").includes("等级判定")))}async function runChar(){if(typeof getAutoResultForTask!=="function"||typeof acceptAndAdvance!=="function")return alert("自动车人模块未初始化"),false;if(state.isSpinning)return false;if(graded()){if(!confirm("当前角色已确定。重新随机？"))return false;restart?.({clearDraft:true});await new Promise(r=>setTimeout(r,0))}let b=document.getElementById("jjkV7RunChar"),n=0;if(b){b.disabled=true;b.textContent="正在车角色…"}try{state.spinToken=Number(state.spinToken||0)+1;state.pendingResult=null;state.isSpinning=false;while(state.currentTask?.type!=="end"&&n<500){let t=state.currentTask,r=getAutoResultForTask(t);if(!r)break;state.pendingResult=r;acceptAndAdvance({render:false});n++;if(t?.nodeId==="grade")break}saveLifeWheelRunDraft?.();renderAll?.();tip(graded()?`角色构筑完成｜${n}步`:`自动中止｜${n}步`);return graded()}catch(e){alert("一键车人失败："+(e?.message||e));return false}finally{if(b){b.disabled=false;b.textContent="一键车完角色"}}}
function age(){try{return Number(getNumericLifeAge?.())||Number(String(state?.flags?.age||"").match(/\d+/)?.[0])||0}catch{return 0}}function ageFactor(t,a){if(a<=22)return t==="学生"?1.25:t==="老师"?.28:/校长|老登/.test(t)?.03:1;if(a<=25)return t==="学生"?.55:t==="老师"?1.25:/校长|老登/.test(t)?.08:1;if(a<=34)return t==="学生"?.02:t==="老师"?2.1:t==="校长"?.35:t==="老登"?.12:1;if(a<=49)return t==="学生"?.01:t==="老师"?1.55:t==="校长"?1.35:t==="老登"?.5:1;return t==="学生"?.002:t==="老师"?.8:t==="校长"?1.75:t==="老登"?2.3:1}
function installAge(){let f=globalThis.getAdjustedWeight;if(typeof f!=="function")return false;if(f.__v7app)return true;let o=f,w=function(task,item,index,base,ctx){let x=Number(o.call(this,task,item,index,base,ctx))||0;if(task?.nodeId!=="highSchoolStatus")return x;let a=age();return a?Math.max(0,x*ageFactor(String(item?.text||""),a)):x};Object.defineProperty(w,"__v7app",{value:true});globalThis.getAdjustedWeight=w;return true}
function bucket(){let s=String(state?.flags?.sorcererGradeLabel||state?.flags?.sorcererGrade||"");if(/特级/.test(s))return"special";if(/一级/.test(s)&&!/准一级/.test(s))return"high";if(/准一级/.test(s))return"mid";return"low"}function patchParade(){let t=state?.currentTask;if(!t||!/百鬼夜行结果（高专方）/.test(String(t.title||""))||t.__v7match)return false;t.battleBridgeOpponents=[...(PARADE[bucket()]||PARADE.low)];t.__v7match=true;return true}
function baseRank(id){let v=state?.flags?.battleBridgePersistentRanks?.[id]||state?.answers?.[id]?.rawText||state?.answers?.[id]?.text||"B";return String(v).toUpperCase().match(/^(EX-|EX|SSS|SS|S|A|B|C|D|E-|E)/)?.[1]||"B"}function shift(id,d){state.flags||={};state.flags.battleBridgePersistentRanks||={};let f=baseRank(id);if(d>0&&f==="EX"){state.flags.v7Transcendence||={};state.flags.v7Transcendence[id]=Number(state.flags.v7Transcendence[id]||0)+1;return`${f}→EX+${state.flags.v7Transcendence[id]}`}let i=Math.max(0,R.indexOf(f)),to=R[Math.max(0,Math.min(R.length-1,i+d))];state.flags.battleBridgePersistentRanks[id]=to;return`${f}→${to}`}
function eraTask(){let e=/持之以恒|刻苦|拼命/.test(String(state?.flags?.effortLevel||""))?3:/摆烂|躺平/.test(String(state?.flags?.effortLevel||""))?0:1,t=Math.max(0,R.indexOf(baseRank("talent"))),g=Math.min(88,22+e*18+t*3),down=e===0?24:e===1?7:2,roll=Math.random()*100,ids=["cursedEnergy","control","efficiency","body","martial"];try{if(isZeroCursedEnergyHeavenlyRestriction?.())ids=ids.filter(x=>!["cursedEnergy","control","efficiency"].includes(x))}catch{}let id=ids[Math.floor(Math.random()*ids.length)]||"martial",fx={kind:"maintain"},text="多年间能力大体维持";if(roll<down){fx={kind:"rank",id,delta:-1};text=`长期状态下滑｜${id}`}else if(roll<down+g){fx={kind:"rank",id,delta:1};text=`时代间积累形成突破｜${id}`}return{type:"computed",nodeId:"eraGapHiddenToVolume0",title:"时代间成长｜怀玉→0卷（约10年）",stage:"时代推进",computedOption:{text,index:0,weight:1,bridgeEffect:fx},options:[{text}]}}
function installStory(){let w=globalThis.JJKPersonalWheel,f=w?.afterCommit;if(typeof f!=="function")return false;if(f.__v7app)return true;let o=f,z=function(p){let out=o.apply(this,arguments);try{let t=p?.task,r=p?.result;if(t?.title==="保卫理子后"&&!state.flags.dead&&!state.flags.eraGapHiddenToVolume0Queued){state.flags.eraGapHiddenToVolume0Queued=true;state.taskQueue.unshift(eraTask())}if(t?.nodeId==="eraGapHiddenToVolume0"){let fx=r?.option?.bridgeEffect||t?.computedOption?.bridgeEffect;if(fx?.kind==="rank"){let rec=(state.records||[]).find(x=>Number(x?.id)===Number(p?.recordId));if(rec)rec.result=`${fx.delta>0?"长期积累形成突破":"长期状态下滑"}｜${fx.id} ${shift(fx.id,Number(fx.delta||0))}`}}if(t?.nodeId==="cursedEnergyNature"&&/具有属性/.test(String(r?.text||""))&&!state.flags.cursedEnergyAttributeDetail&&!(state.taskQueue||[]).some(x=>x?.nodeId==="cursedEnergyAttributeDetail"))state.taskQueue.unshift({type:"choice",nodeId:"cursedEnergyAttributeDetail",title:"咒力属性｜具体性质",stage:"能力风味",options:ATTR.map(text=>({text}))});if(t?.nodeId==="cursedEnergyAttributeDetail")state.flags.cursedEnergyAttributeDetail=String(r?.text||"")}catch(e){console.error(e)}return out};Object.defineProperty(z,"__v7app",{value:true});w.afterCommit=z;return true}
function installBridge(){let b=globalThis.JJKBattleStoryBridge;if(!b)return false;for(const k of["maybeTriggerBattle","autoResolveCurrentTask"]){let f=b[k];if(typeof f!=="function"||f.__v7match)continue;let o=f,w=function(...a){patchParade();return o.apply(this,a)};Object.defineProperty(w,"__v7match",{value:true});b[k]=w}return true}
function recover(){if(!state)return;let s=globalThis.__JJK_FULL_LIFE_SESSION__;if(s&&!s.active&&!globalThis.__JJK_AUTO_FULL_LIFE_ACTIVE__&&(state.isSpinning||state.spinModeSnapshot||state.pendingResult)){try{JJKBattleStoryBridge?.setAutoFullLife?.(false)}catch{}state.isSpinning=false;state.spinModeSnapshot=null;state.pendingResult=null;state.spinToken=Number(state.spinToken||0)+1;let b=document.getElementById("runAllBtn");if(b)b.textContent="一键转完整人生"}}
function css(){if(document.getElementById("v7css"))return;let s=document.createElement("style");s.id="v7css";s.textContent='#jjkV7Difficulty{min-height:38px;border-radius:10px;background:#1b1b22;color:#fff;padding:0 10px}.v7card{width:min(560px,100%);background:#15151b;color:#fff;border:1px solid #ffffff2e;border-radius:18px;padding:16px}.v7head{display:flex;justify-content:space-between}.v7row{display:grid;grid-template-columns:1fr 80px 80px;gap:8px;padding:10px 0;border-top:1px solid #ffffff17}#jjkV7SL{position:fixed;inset:0;z-index:2147483600;background:#000b;display:grid;place-items:center;padding:16px}';document.head.appendChild(s)}function tip(t){let e=document.getElementById("jjkV7Status");if(e)e.textContent=t}
function ui(){if(document.getElementById("jjkV7RunChar"))return true;let r=document.getElementById("runAllBtn");if(!r?.parentElement)return false;let a=document.createElement("button");a.id="jjkV7RunChar";a.className="secondary";a.textContent="一键车完角色";a.onclick=runChar;let b=document.createElement("button");b.className="secondary";b.textContent="SL 存读档";b.onclick=openSL;let d=document.createElement("select");d.id="jjkV7Difficulty";d.innerHTML='<option value="easy">敌方：简单</option><option value="normal">敌方：普通</option><option value="hard">敌方：困难</option>';d.value=gd();d.onchange=()=>sd(d.value);let q=document.createElement("span");q.id="jjkV7Status";q.className="muted";r.after(a);a.after(b);b.after(d);d.after(q);return true}
function tick(){css();ui();installDifficulty();installAge();installStory();installBridge();patchParade();recover();document.documentElement.dataset.jjkAppSystem=`v${V}`}
window.JJKV7App={version:V,saveSlot:save,loadSlot:load,runToCharacter:runChar,getDifficulty:gd,setDifficulty:sd};tick();setInterval(tick,100);console.info(`[JJK-Life-Wheel] V7 app loaded`);
})();
