(() => {
  "use strict";

  const VERSION = "7.0.0";
  const STORY_TYPE = "lifeWheelBattleBridge";
  const LEGACY_TOJI_HEAVY = new Set([
    "card_inverted_spear_of_heaven_pierce",
    "card_chain_of_thousand_miles_bind",
    "card_soul_split_katana_slash"
  ]);
  const RANK = Object.freeze({"E-":0,E:1,D:2,C:3,B:4,A:5,S:6,SS:7,SSS:8,"EX-":9,EX:10});
  const STAT_KEYS = Object.freeze({cursedEnergy:["cursedEnergyScore","cursedEnergy","ce"],control:["controlScore","control"],efficiency:["efficiencyScore","efficiency"],martial:["martialScore","martial"],body:["bodyScore","body"],talent:["talentScore","talent"]});
  const clamp=(v,lo,hi)=>Math.min(hi,Math.max(lo,Number(v)||0));
  const num=(v,fallback=0)=>Number.isFinite(Number(v))?Number(v):fallback;
  const arr=v=>Array.isArray(v)?v:v==null?[]:[v];
  function clone(v){try{return structuredClone(v)}catch{try{return JSON.parse(JSON.stringify(v))}catch{return v&&typeof v==="object"?{...v}:v}}}
  function rankValue(value){if(Number.isFinite(Number(value))&&String(value).trim()!=="")return Math.max(0,Number(value));const m=String(value||"").trim().toUpperCase().match(/^(EX-|EX|SSS|SS|S|A|B|C|D|E-|E)/);return m?RANK[m[1]]:NaN}
  function isLifeWheelProfile(profile){const p=profile||{},text=[p.displayName,p.name,p.notes,p.source,p.sourceType].filter(Boolean).join(" ");return /^战力导入：/.test(String(p.displayName||p.name||""))||/life[-_ ]?wheel|人生转盘|转盘导入/i.test(text)||Boolean(p.encodedCombatProfile)}
  function profileText(x){const p=x?.characterCardProfile||x?.profile||x||{};return[x?.id,x?.name,p.id,p.characterId,p.displayName,p.name,p.visibleGrade,p.officialGrade,p.powerTier,p.notes,...(p.traits||[]),...(p.cardTags||[]),...(p.specialHandTags||[])].filter(Boolean).join(" ")}
  function zeroCe(profile){const text=profileText(profile);return /zero.?ce|零咒力|天与咒缚（肉体强化型）|天与暴君|domainSureHitInvalid/i.test(text)||arr(profile?.flags).some(x=>/zero.?ce/i.test(String(x)))}
  function readFromObject(obj,names){if(!obj||typeof obj!=="object")return NaN;for(const name of names){if(!Object.prototype.hasOwnProperty.call(obj,name))continue;const n=rankValue(obj[name]);if(Number.isFinite(n))return n}return NaN}
  function readStat(profile,id){const p=profile||{},names=STAT_KEYS[id]||[id];for(const source of[p.raw,p.baseStats,p.stats,p]){const n=readFromObject(source,names);if(Number.isFinite(n))return n}return 4}
  function readTechniquePower(profile){const p=profile||{};for(const v of[p.techniquePower,p.technique?.power,p.techniques?.[0]?.power,p.raw?.techniquePower]){const n=rankValue(v);if(Number.isFinite(n))return n}return 4}
  function transcendStepValue(step){const n=Math.max(1,Math.trunc(num(step,1)));return .24/(1+.55*(n-1))}
  function transcendTotal(id){if(typeof state==="undefined")return 0;const legacy=state.flags?.battleBridgeTranscendence||{},current=state.flags?.v7Transcendence||{},count=Math.max(0,Math.trunc(num(current[id]??legacy[id],0)));let total=0;for(let i=1;i<=count;i++)total+=transcendStepValue(i);return total}
  function stat(profile,id){return readStat(profile,id)+(isLifeWheelProfile(profile)?transcendTotal(id):0)}
  function techniquePower(profile){return readTechniquePower(profile)+(isLifeWheelProfile(profile)?transcendTotal("techniquePower"):0)}
  function efficiencyCostMultiplier(efficiency){return Math.exp(-.105*(num(efficiency,4)-4))}
  function bodyResistance(body){const b=Math.max(0,num(body,4));return .015+.39*(1-Math.exp(-b/11.5))}
  function model(profile){const cursedEnergy=stat(profile,"cursedEnergy"),control=stat(profile,"control"),efficiency=stat(profile,"efficiency"),martial=stat(profile,"martial"),body=stat(profile,"body"),talent=stat(profile,"talent"),tech=techniquePower(profile),zce=zeroCe(profile);const bodyOver=Math.max(0,body-6),martialOver=Math.max(0,martial-6);const maxHp=Math.round(Math.max(60,140+24*body+8*martial+4*bodyOver*bodyOver+1.75*martialOver*martialOver));const ceOver=Math.max(0,cursedEnergy-6),ceBase=28+26*cursedEnergy+8*ceOver*ceOver,techniqueCapacityBonus=Math.min(ceBase*.12,tech*3),maxCe=zce?0:Math.round(Math.max(12,ceBase+techniqueCapacityBonus));const physicalOffense=.68*martial+.32*body,techniqueOffense=.46*tech+.24*cursedEnergy+.20*control+.10*talent,defense=.74*body+.26*martial,utility=.42*control+.32*efficiency+.26*talent,major=Math.max(physicalOffense,techniqueOffense),minor=Math.min(physicalOffense,techniqueOffense),combatRating=.56*major+.14*minor+.16*defense+.14*utility;return Object.freeze({cursedEnergy,control,efficiency,martial,body,talent,techniquePower:tech,zeroCe:zce,maxHp,maxCe,ceCostMultiplier:efficiencyCostMultiplier(efficiency),bodyResistance:bodyResistance(body),physicalOffense,techniqueOffense,defense,utility,combatRating})}
  function actionText(action){return[action?.id,action?.actionId,action?.cardId,action?.name,action?.label,action?.type,action?.cardType,action?.damageType,action?.scalingProfile,action?.risk,action?.effectSummary,...(action?.tags||[]),...(action?.specialHandTags||[])].filter(Boolean).join(" ").toLowerCase()}
  function actionArchetype(action){const t=actionText(action);if(/heal|healing|rct|reverse|治疗|疗伤|回复|support|resource|防御|guard|block/.test(t))return"utility";const physical=/melee|physical|martial|体术|近身|拳|踢|咒具|cursed_tool|weapon|刀|剑|chain/.test(t),technique=/technique|innate|术式|咒法|curse|beam|projectile|domain|领域|必中|blue|red|purple|苍|赫|茈|御厨子|shrine|maximum/.test(t);if(physical&&technique)return"hybrid";if(physical)return"physical";return technique?"technique":"generic"}
  function actionTier(action){const t=actionText(action);if(/茈|虚式|hollow.?purple|极之番|極ノ番|maximum|最大出力|最大输出|终结|終結|finisher|ultimate|世界斩|world.?slash|fuga|灶/.test(t))return"ultimate";if(/high|critical|burst|爆发|大功率|高出力|高输出|领域|domain/.test(t)||/high|critical/.test(String(action?.risk||"")))return"high";return"normal"}
  function genericTechniqueMultiplier(actorProfile,action){const kind=actionArchetype(action),m=model(actorProfile);if(kind==="physical")return 1;if(kind==="hybrid"){const f=Math.exp(.085*(m.techniqueOffense-4));return Math.sqrt(Math.max(.45,f))}if(kind==="technique"||kind==="generic")return Math.exp(.085*(m.techniqueOffense-4));return 1}
  function directTechniqueMultiplier(actor,card){const weights=globalThis.JJKBattleDataDirect?.getBattleCardCoreWeights?.(card)||{martial:0,technique:1},techWeight=clamp(num(weights.technique,0),0,1);if(techWeight<=0)return 1;const m=model(actor),missingTechnique=m.techniquePower-m.control;return Math.exp(.07*missingTechnique*techWeight)}
  function normalizeScaling(card){if(!card?.scaling)return card;const c=clone(card);c.scaling={...c.scaling};const s=c.scaling;s.bodyResistanceBase=.10;s.bodyResistancePerRank=.025;s.bodyResistanceMin=.025;s.bodyResistanceMax=.42;s.martialEvasionPerRank=.025;s.efficiencyCostPerRank=.07;s.efficiencyCostMin=.48;s.efficiencyCostMax=1.55;s.sourceDamageMin=Math.min(num(s.sourceDamageMin,.25),.25);s.sourceDamageMax=Math.max(num(s.sourceDamageMax,2.5),3.2);return c}
  function isStoryBattle(battle){return String(battle?.activityContext?.type||"")===STORY_TYPE}
  function isPlayerActor(actor){return String(actor?.side||"")==="left"||isLifeWheelProfile(actor?.characterCardProfile||actor?.profile||actor)}
  function scaleDamageFields(action,multiplier){const m=num(multiplier,1);for(const[obj,key]of[[action,"damage"],[action,"baseDamage"],[action?.effect,"damage"]])if(obj&&Number.isFinite(Number(obj[key]))&&Number(obj[key])>0)obj[key]=Number((Number(obj[key])*m).toFixed(4))}
  function neutralizeEmbeddedTojiHotfix(action,actor){const id=String(action?.id||action?.actionId||action?.cardId||"");if(!LEGACY_TOJI_HEAVY.has(id)||!/伏黑甚尔（怀玉|toji_fushiguro_hidden_inventory/i.test(profileText(actor)))return action;const c=clone(action);scaleDamageFields(c,1/.82);return c}
  function projectionRatio(action){const tier=actionTier(action);return tier==="ultimate"?.90:tier==="high"?.80:.72}
  function softBurstDamage(rawDamage,maxHp,tier,attackerRating,defenderRating){const raw=Math.max(0,num(rawDamage,0)),hp=Math.max(1,num(maxHp,1));if(raw<=0)return 0;const ratio=Math.max(.2,num(attackerRating,4)/Math.max(.5,num(defenderRating,4))),gap=Math.max(0,ratio-1),gapEase=1-Math.exp(-gap),baseThreshold=tier==="ultimate"?.62:tier==="high"?.46:.34,baseRetention=tier==="ultimate"?.86:tier==="high"?.56:.35,thresholdFraction=baseThreshold+(tier==="ultimate"?.20:.17)*gapEase,retention=baseRetention+(1-baseRetention)*.62*gapEase,threshold=hp*thresholdFraction;return raw<=threshold?raw:threshold+(raw-threshold)*retention}
  function mutateResultHp(result,afterHp,appliedDamage){if(!result||typeof result!=="object")return;const seen=new Set,walk=obj=>{if(!obj||typeof obj!=="object"||seen.has(obj))return;seen.add(obj);if("afterHp"in obj&&Number.isFinite(Number(obj.afterHp)))obj.afterHp=Number(afterHp.toFixed(1));if("defeated"in obj)obj.defeated=afterHp<=0;if("overkill"in obj&&afterHp>0)obj.overkill=0;Array.isArray(obj)?obj.forEach(walk):Object.values(obj).forEach(walk)};walk(result);result.v7AppliedDamage=Number(appliedDamage.toFixed(1))}
  function installResourceModel(){const api=globalThis.JJKDuelResource;if(!api||typeof api.deriveDuelResourcesFromProfile!=="function")return false;if(api.deriveDuelResourcesFromProfile.__jjkV7Data)return true;const old=api.deriveDuelResourcesFromProfile,wrapped=function(profile,card,side){const resource=old.call(this,profile,card,side);if(!resource)return resource;const m=model(profile);resource.maxHp=m.maxHp;resource.hp=m.maxHp;resource.maxCe=m.maxCe;resource.ce=m.maxCe;resource.ceCostMultiplier=m.ceCostMultiplier;resource.bodyResistance=m.bodyResistance;resource.regenRatio=m.zeroCe?0:.02+.11*(1-Math.exp(-(m.control+m.efficiency)/16));resource.ceRegen=m.zeroCe?0:Number((resource.maxCe*resource.regenRatio).toFixed(1));resource.v7Model={...m};resource.raw={...(resource.raw||{}),cursedEnergyScore:m.cursedEnergy,controlScore:m.control,efficiencyScore:m.efficiency,martialScore:m.martial,bodyScore:m.body,talentScore:m.talent};return resource};Object.defineProperty(wrapped,"__jjkV7Data",{value:true});api.deriveDuelResourcesFromProfile=wrapped;return true}
  function installDirectCardModel(){const api=globalThis.JJKBattleDataDirect;if(!api||typeof api.calculateBattleCardSettlement!=="function")return false;if(api.calculateBattleCardSettlement.__jjkV7Data)return true;const old=api.calculateBattleCardSettlement,wrapped=function(card,actor,opponent,options){const normalized=normalizeScaling(card),result=old.call(this,normalized,actor,opponent,options);if(!result||num(result.damage,0)<=0)return result;const multiplier=directTechniqueMultiplier(actor,normalized);if(Math.abs(multiplier-1)<.002)return result;result.damage=Number((num(result.damage,0)*multiplier).toFixed(1));if(result.damageBreakdown&&typeof result.damageBreakdown==="object")result.damageBreakdown.v7TechniquePowerMultiplier=Number(multiplier.toFixed(4));result.v7TechniquePowerMultiplier=Number(multiplier.toFixed(4));return result};Object.defineProperty(wrapped,"__jjkV7Data",{value:true});try{globalThis.JJKBattleDataDirect=Object.freeze({...api,calculateBattleCardSettlement:wrapped});return true}catch{try{api.calculateBattleCardSettlement=wrapped;return true}catch{return false}}}
  function installActionModel(){const api=globalThis.JJKDuelActions;if(!api||typeof api.applyDuelActionEffect!=="function")return false;if(api.applyDuelActionEffect.__jjkV7Data)return true;const old=api.applyDuelActionEffect,wrapped=function(action,actor,opponent,battle){let normalized=neutralizeEmbeddedTojiHotfix(action,actor);const actorProfile=actor?.characterCardProfile||actor?.profile||actor||{};if(isStoryBattle(battle)&&isPlayerActor(actor)){normalized=clone(normalized);if(!normalized.scaling&&normalized.type!=="card_template_runtime"){normalized.projectionRuntime={...(normalized.projectionRuntime||{}),active:true,damageSettlementRatio:projectionRatio(normalized)};normalized.projectionDamageSettlementRatio=projectionRatio(normalized);const multiplier=genericTechniqueMultiplier(actorProfile,normalized);if(multiplier!==1){scaleDamageFields(normalized,multiplier);normalized.v7TechniquePowerMultiplier=Number(multiplier.toFixed(4))}}}const before=num(opponent?.hp,0),maxHp=Math.max(1,num(opponent?.maxHp,before||1)),result=old.call(this,normalized,actor,opponent,battle);if(!opponent||before<=0)return result;const after=num(opponent.hp,0),rawLoss=Math.max(0,before-after);if(rawLoss<=0)return result;const attackerModel=model(actorProfile),defenderProfile=opponent?.characterCardProfile||opponent?.profile||opponent||{},defenderModel=model(defenderProfile),tier=actionTier(normalized),softened=Math.min(before,softBurstDamage(rawLoss,maxHp,tier,attackerModel.combatRating,defenderModel.combatRating));if(softened+.5<rawLoss){opponent.hp=Math.max(0,Number((before-softened).toFixed(1)));mutateResultHp(result,opponent.hp,softened);try{(battle?.resourceLog||battle?.log)?.unshift?.({side:opponent.side||"right",title:"V7 单行动爆发曲线",detail:`${tier==="ultimate"?"终结技":tier==="high"?"高输出":"常规行动"}原实际损失 ${rawLoss.toFixed(1)}，经统一软压缩后 ${softened.toFixed(1)}；不是硬上限，超出部分仍继续增长。`,type:"system",delta:{v7BurstCurve:true,rawLoss,softened,tier}})}catch{}}return result};Object.defineProperty(wrapped,"__jjkV7Data",{value:true});api.applyDuelActionEffect=wrapped;return true}
  function installRules(){if(typeof state==="undefined")return false;if(state.duelResourceRules?.hp)state.duelResourceRules.hp.max=Number.MAX_SAFE_INTEGER;if(state.duelResourceRules?.ce)state.duelResourceRules.ce.max=Number.MAX_SAFE_INTEGER;return true}
  function install(){const ok=[installRules(),installResourceModel(),installDirectCardModel(),installActionModel()].every(Boolean);if(ok){document.documentElement.dataset.jjkDataSystem=`v${VERSION}`;window.JJK_V7_DATA_READY=true}return ok}
  window.JJKV7Data=Object.freeze({version:VERSION,rankValue,stat,techniquePower,transcendStepValue,transcendTotal,model,bodyResistance,efficiencyCostMultiplier,actionArchetype,actionTier,softBurstDamage});let attempts=0;const timer=setInterval(()=>{attempts+=1;if(install()||attempts>400)clearInterval(timer)},50);install();console.info(`[JJK-Life-Wheel] unified data system v${VERSION} loading`);
})();
